FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG NZBHYDRA2_VERSION=''
ARG NZBHYDRA2_ARCH='generic'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm'  \
    NZBHYDRA2_VERSION="${NZBHYDRA2_VERSION}" \
    NZBHYDRA2_ARCH="${NZBHYDRA2_ARCH}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk add --no-cache --virtual=build-deps \
      curl \
      unzip \
    && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      openjdk17-jre-headless \
      python3 \
    && \
    curl -sL https://github.com/theotherp/nzbhydra2/releases/download/v${NZBHYDRA2_VERSION}/nzbhydra2-${NZBHYDRA2_VERSION}-${NZBHYDRA2_ARCH}.zip -o /tmp/nzbhydra2.zip && \
    cd /tmp && \
    unzip /tmp/nzbhydra2.zip -d /opt/nzbhydra2 && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    mkdir -p /config && \
    rm -rf /opt/nzbhydra2/data && \
    ln -snf /config /opt/nzbhydra2/data && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* 

### Volume
VOLUME ["/config"]

### Expose ports
EXPOSE 5076
